#import <Foundation/Foundation.h>
#import "BharatMapsGeometry.h"
#import "BharatMapsMapCamera.h"
#import "BharatMapsStyle.h"
#import "BharatMapsTypes.h"

NS_ASSUME_NONNULL_BEGIN

@class BharatMapsAnnotationImage;
@class BharatMapsShape;
@class BharatMapsPolyline;
@class BharatMapsPolygon;

@protocol BharatMapsMapSnapshotterDelegate;
@protocol BharatMapsAnnotation;

/**
 An overlay that is placed within a ``BharatMapsMapSnapshot``.
 To access this object, use ``BharatMapsMapSnapshotter/startWithOverlayHandler:completionHandler:``.
 */

BharatMaps_EXPORT
@interface BharatMapsMapSnapshotOverlay : NSObject

/**
 The current `CGContext` that snapshot is drawing within. You may use this context
 to perform additional custom drawing.
 */
@property (nonatomic, readonly) CGContextRef context;

#if TARGET_OS_IPHONE
/**
 Converts the specified map coordinate to a point in the coordinate space of the
 context.
 */
- (CGPoint)pointForCoordinate:(CLLocationCoordinate2D)coordinate;

/**
 Converts the specified context point to a map coordinate.
 */
- (CLLocationCoordinate2D)coordinateForPoint:(CGPoint)point;

#else
/**
 Converts the specified map coordinate to a point in the coordinate space of the
 context.
 */
- (NSPoint)pointForCoordinate:(CLLocationCoordinate2D)coordinate;

/**
 Converts the specified context point to a map coordinate.
 */
- (CLLocationCoordinate2D)coordinateForPoint:(NSPoint)point;
#endif

@end

/**
A block provided during the snapshot drawing process, enabling the ability to
draw custom overlays rendered with Core Graphics.

 @param snapshotOverlay The ``BharatMapsMapSnapshotOverlay`` provided during snapshot drawing.
 */
typedef void (^BharatMapsMapSnapshotOverlayHandler)(BharatMapsMapSnapshotOverlay *snapshotOverlay);

/**
 The options to use when creating images with the ``BharatMapsMapSnapshotter``.
 */
BharatMaps_EXPORT
@interface BharatMapsMapSnapshotOptions : NSObject <NSCopying>

/**
 Creates a set of options with the minimum required information.

 @param styleURL URL of the map style to snapshot. The URL may be a full HTTP,
    HTTPS URL, canonical URL or a path to a local file relative to
    the application's resource path. Specify `nil` for the default style.
 @param camera The camera representing the viewport visible in the snapshot.
 @param size The image size.
 */
- (instancetype)initWithStyleURL:(nullable NSURL *)styleURL
                          camera:(BharatMapsMapCamera *)camera
                            size:(CGSize)size;

// MARK: - Configuring the Map

/**
 Whether to include the MapLibre logo. Note this is not required.
 */
@property (nonatomic, readwrite) BOOL showsLogo;

/**
 Whether to add attribution from the sources on the snapshots. Enabled by default.
 */
@property (nonatomic, readwrite) BOOL showsAttribution;

/**
 URL of the map style to snapshot.
 */
@property (nonatomic, readonly) NSURL *styleURL;

/**
 The zoom level.

 The default zoom level is 0. If this property is non-zero and the camera
 property is non-nil, the camera’s altitude is ignored in favor of this
 property’s value.
 */
@property (nonatomic) double zoomLevel;

/**
 A camera representing the viewport visible in the snapshot.

 If this property is non-nil and the ``coordinateBounds`` property is set to a
 non-empty coordinate bounds, the camera’s center coordinate and altitude are
 ignored in favor of the ``coordinateBounds`` property.
 */
@property (nonatomic) BharatMapsMapCamera *camera;

/**
 The coordinate rectangle that encompasses the bounds to capture.

 If this property is non-empty and the camera property is non-nil, the camera’s
 center coordinate and altitude are ignored in favor of this property’s value.
 */
@property (nonatomic) BharatMapsCoordinateBounds coordinateBounds;

// MARK: - Configuring the Image

/**
 The size of the output image, measured in points.

 */
@property (nonatomic, readonly) CGSize size;

/**
 The scale of the output image. Defaults to the main screen scale.

 The minimum scale is 1.
 */
@property (nonatomic) CGFloat scale;

@end

/**
 An image generated by a snapshotter object.
 */
BharatMaps_EXPORT
@interface BharatMapsMapSnapshot : NSObject

#if TARGET_OS_IPHONE
/**
 Converts the specified map coordinate to a point in the coordinate space of the
 image.
 */
- (CGPoint)pointForCoordinate:(CLLocationCoordinate2D)coordinate;

/**
 Converts the specified image point to a map coordinate.
 */
- (CLLocationCoordinate2D)coordinateForPoint:(CGPoint)point;

/**
 The image of the map’s content.
 */
@property (nonatomic, readonly) UIImage *image;
#else
/**
 Converts the specified map coordinate to a point in the coordinate space of the
 image.
 */
- (NSPoint)pointForCoordinate:(CLLocationCoordinate2D)coordinate;

/**
 Converts the specified image point to a map coordinate.
 */
- (CLLocationCoordinate2D)coordinateForPoint:(NSPoint)point;

/**
 The image of the map’s content.
 */
@property (nonatomic, readonly) NSImage *image;
#endif

@end

/**
 A block to processes the result or error of a snapshot request.

 @param snapshot The ``BharatMapsMapSnapshot`` that was generated or `nil` if an error
    occurred.
 @param error The error that occured or `nil` when successful.
 */
typedef void (^BharatMapsMapSnapshotCompletionHandler)(BharatMapsMapSnapshot *_Nullable snapshot,
                                                NSError *_Nullable error);

/**
 An ``BharatMapsMapSnapshotter`` generates static raster images of the map. Each snapshot
 image depicts a portion of a map defined by an ``BharatMapsMapSnapshotOptions`` object
 you provide. The snapshotter generates an ``BharatMapsMapSnapshot`` object
 asynchronously, calling ``BharatMapsMapSnapshotterDelegate`` methods if defined, then
 passing it into a completion handler once tiles and other resources needed for
 the snapshot are finished loading.

 You can change the snapshotter’s options at any time and reuse the snapshotter
 for multiple distinct snapshots; however, the snapshotter can only generate one
 snapshot at a time. If you need to generate multiple snapshots concurrently,
 create multiple snapshotter objects.

 For an interactive map, use the ``BharatMapsMapView`` class. Both ``BharatMapsMapSnapshotter``
 and ``BharatMapsMapView`` are compatible with offline packs managed by the
 ``BharatMapsOfflineStorage`` class.

 From a snapshot, you can obtain an image and convert geographic coordinates to
 the image’s coordinate space in order to superimpose markers and overlays. If
 you do not need offline map functionality, you can use the `Snapshot` class in
 [MapboxStatic.swift](https://github.com/mapbox/MapboxStatic.swift/) to generate
 static map images with overlays.

 ### Example

 ```swift
 let camera = BharatMapsMapCamera(lookingAtCenter: CLLocationCoordinate2D(latitude: 37.7184, longitude:
 -122.4365), altitude: 100, pitch: 20, heading: 0)

 let options = BharatMapsMapSnapshotOptions(styleURL: BharatMapsStyle.satelliteStreetsStyleURL, camera: camera,
 size: CGSize(width: 320, height: 480)) options.zoomLevel = 10

 let snapshotter = BharatMapsMapSnapshotter(options: options)
 snapshotter.start { (snapshot, error) in
     if let error = error {
         fatalError(error.localizedDescription)
     }

     image = snapshot?.image
 }
 ```

 #### Related examples
 TODO: Create a static map snapshot, learn how to use the
 ``BharatMapsMapSnapshotter`` to generate a static image based on an ``BharatMapsMapSnapshotter``
 object's style, camera, and view bounds.
 */
BharatMaps_EXPORT
@interface BharatMapsMapSnapshotter : NSObject <BharatMapsStylable>

- (instancetype)init NS_UNAVAILABLE;

/**
 Initializes and returns a map snapshotter object that produces snapshots
 according to the given options.

 @param options The options to use when generating a map snapshot.
 @return An initialized map snapshotter.
 */
- (instancetype)initWithOptions:(BharatMapsMapSnapshotOptions *)options NS_DESIGNATED_INITIALIZER;

/**
 Adds an annotation to the snapshotter.

 > Note: ``BharatMapsMultiPolyline``, ``BharatMapsMultiPolyline``, ``BharatMapsMultiPolyline``, and
    ``BharatMapsPointCollection`` objects cannot be added to the snapshotter at this time.
    Any multipoint, multipolyline, multipolygon, shape or point collection
    object that is specified is silently ignored.

 @param annotation The annotation object to add to the receiver. This object
    must conform to the ``BharatMapsAnnotation`` protocol. The snapshotter retains the
    annotation object.
 */
- (void)addAnnotation:(id<BharatMapsAnnotation>)annotation;

/**
 Adds an array of annotations to the snapshotter.

 > Note: ``BharatMapsMultiPolyline``, ``BharatMapsMultiPolyline``, and ``BharatMapsMultiPolyline`` objects
    cannot be added to the snapshotter at this time. Nor can ``BharatMapsMultiPoint``
    objects that are not instances of ``BharatMapsPolyline`` or ``BharatMapsPolyline``. Any
    multipoint, multipolyline, multipolygon, or shape collection objects that
    are specified are silently ignored.

 @param annotations An array of annotation objects. Each object in the array
    must conform to the ``BharatMapsAnnotation`` protocol. The snapshotter retains each
    individual annotation object.
 */
- (void)addAnnotations:(NSArray<id<BharatMapsAnnotation>> *)annotations;

/**
 Starts the snapshot creation and executes the specified block with the result.

 @param completionHandler The block to call with a finished snapshot. The block
    is executed on the main queue.
 */
- (void)startWithCompletionHandler:(BharatMapsMapSnapshotCompletionHandler)completionHandler;

/**
 Starts the snapshot creation and executes the specified block with the result
 on the specified queue.

 @param queue The queue on which to call the block specified in the
    `completionHandler` parameter.
 @param completionHandler The block to call with a finished snapshot. The block
     is executed on the queue specified in the `queue` parameter.
 */
- (void)startWithQueue:(dispatch_queue_t)queue
     completionHandler:(BharatMapsMapSnapshotCompletionHandler)completionHandler;

/**
 Starts the snapshot creation and executes the specified blocks with the result
 on the specified queue. Use this option if you want to add custom drawing on
 top of the resulting ``BharatMapsMapSnapshot``.

 @param overlayHandler The block to call after the base map finishes drawing but
    before certain built-in overlays draw. The block can use Core Graphics to
    draw custom content directly over the base map. The block is executed on a
    background queue.
 @param completionHandler The block to call with a finished snapshot. The block
     is executed on the main queue.
 */
- (void)startWithOverlayHandler:(BharatMapsMapSnapshotOverlayHandler)overlayHandler
              completionHandler:(BharatMapsMapSnapshotCompletionHandler)completionHandler;

/**
 Cancels the snapshot creation request, if any.

 Once you call this method, you cannot resume the snapshot. In order to obtain
 the snapshot, create a new ``BharatMapsMapSnapshotter`` object.
 */
- (void)cancel;

/**
 The options to use when generating a map snapshot.
 */
@property (nonatomic) BharatMapsMapSnapshotOptions *options;

/**
 Indicates whether a snapshot is currently being generated.
 */
@property (nonatomic, readonly, getter=isLoading) BOOL loading;

/**
 The snapshotter’s delegate.

 The delegate is responsible for responding to significant changes during the
 snapshotting process, such as the style loading. Implement a delegate to
 customize the style that is depicted by the snapshot.

 You set the delegate after initializing the snapshotter but before receiving
 the snapshot, typically before starting the snapshot. The snapshotter keeps a
 weak reference to its delegate, so you must keep a strong reference to it to
 ensure that your style customizations apply.
 */
@property (nonatomic, weak) id<BharatMapsMapSnapshotterDelegate> delegate;

/**
 The style displayed in the resulting snapshot.

 Unlike the ``BharatMapsMapSnapshotOptions/styleURL`` property, this property is set to
 an object that allows you to manipulate every aspect of the style locally.

 This property is set to `nil` until the style finishes loading. If the style
 has failed to load, this property is set to `nil`. Because the style loads
 asynchronously, you should manipulate it in the
 ``BharatMapsMapSnapshotterDelegate/mapSnapshotter:didFinishLoadingStyle:`` method. It
 is not possible to manipulate the style before it has finished loading.
 */
@property (nonatomic, readonly, nullable) BharatMapsStyle *style;

@end

/**
 Optional methods about significant events when creating a snapshot using an
 ``BharatMapsMapSnapshotter`` object.
 */
@protocol BharatMapsMapSnapshotterDelegate <NSObject>
@optional

/**
 Tells the delegate that the snapshotter was unable to load data needed for
 snapshotting the map.

 This method may be called for a variety of reasons, including a network
 connection failure or a failure to fetch the style from the server. You can use
 the given error message to notify the user that map data is unavailable.

 @param snapshotter The snapshotter that is unable to load the data.
 @param error The reason the data could not be loaded.
*/
- (void)mapSnapshotterDidFail:(BharatMapsMapSnapshotter *)snapshotter withError:(NSError *)error;

/**
 Tells the delegate that the snapshotter has just finished loading a style.

 This method is called in response to
 ``BharatMapsMapSnapshotter/startWithQueue:completionHandler:`` as long as the
 ``BharatMapsMapSnapshotter/delegate`` property is set. Changes to sources or layers of
 the style being snapshotted do not cause this method to be called.

 @param snapshotter The snapshotter that has just loaded a style.
 @param style The style that was loaded.
 */
- (void)mapSnapshotter:(BharatMapsMapSnapshotter *)snapshotter didFinishLoadingStyle:(BharatMapsStyle *)style;

- (void)mapSnapshotter:(BharatMapsMapSnapshotter *)snapshotter didFailLoadingImageNamed:(NSString *)name;

/**
 Returns an annotation image object to mark the given point annotation object on
 the map.

 Implement this method to mark a point annotation with a static image.

 Static annotation images use less memory and draw more quickly than annotation
 views. On the other hand, annotation views are compatible with UIKit, Core
 Animation, and other Cocoa Touch frameworks.

 @param snapshotter The snapshotter that has just loaded a style.
 @param annotation The object representing the annotation that is about to be
    displayed.
 @return The annotation image object to display for the given annotation or
    `nil` if you want to display the default marker image or an annotation view.
*/
- (nullable BharatMapsAnnotationImage *)mapSnapshotter:(BharatMapsMapSnapshotter *)snapshotter
                             imageForAnnotation:(id<BharatMapsAnnotation>)annotation;

/**
 Returns the alpha value to use when rendering a shape annotation.

 A value of `0.0` results in a completely transparent shape. A value of `1.0`,
 the default, results in a completely opaque shape.

 This method sets the opacity of an entire shape, inclusive of its stroke and
 fill. To independently set the values for stroke or fill, specify an alpha
 component in the color returned by `-mapSnapshotter:strokeColorForShapeAnnotation:` or
 `-mapSnapshotter:fillColorForPolygonAnnotation:`.

 @param snapshotter The snapshotter that has just loaded a style.
 @param annotation The annotation being rendered.
 @return An alpha value between `0` and `1.0`.
 */
- (CGFloat)mapSnapshotter:(BharatMapsMapSnapshotter *)snapshotter
    alphaForShapeAnnotation:(BharatMapsShape *)annotation;

/**
 Returns the color to use when rendering the outline of a shape annotation.

 The default stroke color is BharatMapsColor.whiteColor.

 Opacity may be set by specifying an alpha component. The default alpha value is
 `1.0` and results in a completely opaque stroke.

 @param snapshotter The snapshotter that has just loaded a style.
 @param annotation The annotation being rendered.
 @return A color to use for the shape outline.

 */
- (BharatMapsColor *)mapSnapshotter:(BharatMapsMapSnapshotter *)snapshotter
    strokeColorForShapeAnnotation:(BharatMapsShape *)annotation;

/**
 Returns the color to use when rendering the fill of a polygon annotation.

 The default fill color is the BharatMapsColor.whiteColor.

 Opacity may be set by specifying an alpha component. The default alpha value is
 `1.0` and results in a completely opaque shape.

 @param snapshotter The snapshotter that has just loaded a style.
 @param annotation The annotation being rendered.
 @return The polygon’s interior fill color.

 */
- (BharatMapsColor *)mapSnapshotter:(BharatMapsMapSnapshotter *)snapshotter
    fillColorForPolygonAnnotation:(BharatMapsPolygon *)annotation;

/**
 Returns the line width in points to use when rendering the outline of a
 polyline annotation.

 By default, the polyline is outlined with a line `3.0` points wide.

 @param snapshotter The snapshotter that has just loaded a style.
 @param annotation The annotation being rendered.
 @return A line width for the polyline, measured in points.

 */
- (CGFloat)mapSnapshotter:(BharatMapsMapSnapshotter *)snapshotter
    lineWidthForPolylineAnnotation:(BharatMapsPolyline *)annotation;

@end

NS_ASSUME_NONNULL_END
